### ISSUE TITLE
Error at every actions

### ISSUE THREAD

**Issue by Impre-visible** [TahaGorme/slashy#13]
Hi, when I start the script it's okay, but when an account do a single action, I have a lot of errors, I increase the delay of every actions, and same problem, here's the logs :
```js
ReferenceError: item is not defined
    at autoToolBuyer (C:\Users\Manafix\Desktop\slashy-main\index.js:1010:36)
    at Client.<anonymous> (C:\Users\Manafix\Desktop\slashy-main\index.js:402:3)
    at Client.emit (node:events:390:28)
    at MessageCreateAction.handle (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\actions\MessageCreate.js:30:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:359:31)
    at WebSocketShard.onPacket (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:324:10)
    at WebSocket.onMessage (C:\Users\Manafix\Desktop\slashy-main\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:390:28) Promise {
  <rejected> ReferenceError: item is not defined
      at autoToolBuyer (C:\Users\Manafix\Desktop\slashy-main\index.js:1010:36)
      at Client.<anonymous> (C:\Users\Manafix\Desktop\slashy-main\index.js:402:3)
      at Client.emit (node:events:390:28)
      at MessageCreateAction.handle (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\actions\MessageCreate.js:30:14)
      at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
      at WebSocketManager.handlePacket (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:359:31)
      at WebSocketShard.onPacket (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:489:22)
      at WebSocketShard.onMessage (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:324:10)
      at WebSocket.onMessage (C:\Users\Manafix\Desktop\slashy-main\node_modules\ws\lib\event-target.js:199:18)
      at WebSocket.emit (node:events:390:28)
}
 [Anti Crash] >>  Unhandled Rejection/Catch
ReferenceError: item is not defined
    at autoToolBuyer (C:\Users\Manafix\Desktop\slashy-main\index.js:1010:36)
    at Client.<anonymous> (C:\Users\Manafix\Desktop\slashy-main\index.js:402:3)
    at Client.emit (node:events:390:28)
    at MessageCreateAction.handle (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\actions\MessageCreate.js:30:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:359:31)
    at WebSocketShard.onPacket (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:324:10)
    at WebSocket.onMessage (C:\Users\Manafix\Desktop\slashy-main\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:390:28) Promise {
  <rejected> ReferenceError: item is not defined
      at autoToolBuyer (C:\Users\Manafix\Desktop\slashy-main\index.js:1010:36)
      at Client.<anonymous> (C:\Users\Manafix\Desktop\slashy-main\index.js:402:3)
      at Client.emit (node:events:390:28)
      at MessageCreateAction.handle (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\actions\MessageCreate.js:30:14)
      at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
      at WebSocketManager.handlePacket (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:359:31)
      at WebSocketShard.onPacket (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:489:22)
      at WebSocketShard.onMessage (C:\Users\Manafix\Desktop\slashy-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:324:10)
      at WebSocket.onMessage (C:\Users\Manafix\Desktop\slashy-main\node_modules\ws\lib\event-target.js:199:18)
      at WebSocket.emit (node:events:390:28)
}
 [Anti Crash] >>  Unhandled Rejection/Catch
ReferenceError: item is not defined
    at autoToolBuyer (C:\Users\Manafix\Desktop\slashy-main\index.js:1010:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) Promise {
  <rejected> ReferenceError: item is not defined
      at autoToolBuyer (C:\Users\Manafix\Desktop\slashy-main\index.js:1010:36)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}
```

**Comment by TahaGorme** [comment]
its fixed in the latest update :)
