### ISSUE TITLE
while running slashy 24/7 i get an error.

### ISSUE THREAD

**Issue by OxyZachary** [TahaGorme/slashy#20]
```
     at async randomCommand (/root/slashy/index.js:1184:7)

 TypeError: Cannot read properties of undefined (reading 'type')

     at parseOption (/root/slashy/node_modules/discord.js-selfbot-v13
/src/structures/ApplicationCommand.js:640:59)

     at ApplicationCommand.sendSlashCommand (/root/slashy/node_module
s/discord.js-selfbot-v13/src/structures/ApplicationCommand.js:898:17)

     at TextChannel.sendSlash (/root/slashy/node_modules/discord.js-s
elfbot-v13/src/structures/interfaces/TextBasedChannel.js:475:26)

     at process.processTicksAndRejections (node:internal/process/task
_queues:95:5)

     at async randomCommand (/root/slashy/index.js:1184:7)

 TypeError: Cannot read properties of undefined (reading 'type')

     at parseOption (/root/slashy/node_modules/discord.js-selfbot-v13
/src/structures/ApplicationCommand.js:640:59)

     at ApplicationCommand.sendSlashCommand (/root/slashy/node_module
s/discord.js-selfbot-v13/src/structures/ApplicationCommand.js:898:17)

     at TextChannel.sendSlash (/root/slashy/node_modules/discord.js-s
elfbot-v13/src/structures/interfaces/TextBasedChannel.js:475:26)

     at process.processTicksAndRejections (node:internal/process/task
_queues:95:5)

     at async randomCommand (/root/slashy/index.js:1184:7)
```
the error stops all slashy's commands for some reason

**Comment by TahaGorme** [comment]
can you remove autoscratch from your config.json?

**Comment by OxyZachary** [comment]
its fixed by removing scratch from my config but i did have a valid value of `autoScratch > scratchAmount` in the config
